create table if not exists public.garcar_entitlements (
  id bigint generated by default as identity primary key,
  stripe_event_id text not null unique,
  checkout_session_id text not null unique,
  stripe_customer_id text not null,
  hubspot_contact_id text not null,
  plan text not null,
  customer_email text not null,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists garcar_entitlements_customer_idx
  on public.garcar_entitlements (stripe_customer_id);

create index if not exists garcar_entitlements_hubspot_idx
  on public.garcar_entitlements (hubspot_contact_id);

alter table public.garcar_entitlements enable row level security;

-- Service-role writes are used by the backend. No public client policy is created.
